#!/bin/sh

export LD_LIBRARY_PATH="$(pwd)"

## The input_file.so plugin watches a folder for new files, it does not matter where
## the JPEG files orginate from. For instance it is possible to grab the desktop and 
## store the files to a folder:
# while true; do xwd -root | convert - -scale 640 /tmp/input/bla.jpg; sleep 0.5; done &
## Then the files can be read from the folder "/tmp/input" and served via HTTP
 rm -fr /tmp/driver-camera/*
 mkdir -p /tmp/driver-camera
 mjpg_streamer -i "input_file.so -f /tmp/driver-camera -r -d 0.1" -o "output_http.so -w www -p 5004"


