#!/bin/sh

export LD_LIBRARY_PATH="$(pwd)"

 rm -fr /tmp/driver-camera/*
 mkdir -p /tmp/driver-camera
 mjpg_streamer -i "input_file.so -f /tmp/driver-camera -r -d 0.1" -o "output_http.so -w www -p 5004"


