#!/bin/bash

echo $#

export CENTER=0
export LEFT=1
export RIGHT=2

export POSITION=$CENTER

if [ "$#" -eq 1 ]; then
    export POSITION="$1"
fi

echo position=$POSITION

rm -fr /tmp/*-camera
mkdir -p /tmp/shooter-camera /tmp/driver-camera
cd ~/Robotics/MentorRepository/Software/workspace/JSim2018Bot;

killall gzserver
ant jar-for-simulation

roxterm --title="Gazebo Simulation" --tab-name=gazebo -e start_gazebo $POSITION;
sleep 1;
roxterm --tab --tab-name=driver-camera -e start_driver_camera;
sleep 1;
roxterm --tab --tab-name=java -e start_java $POSITION;
sleep 3;
roxterm --tab --tab-name=dashboard -e start_smartdashboard;
sleep 3;
roxterm --tab --tab-name=sim_ds -e sim_ds;

