package org.usfirst.frc.team159.robot;

public interface PhysicalConstants {
  double ROBOT_WIDTH = 34.25;
  double ROBOT_LENGTH = 38.5;

  double FIELD_WIDTH = 324;
  double FIELD_LENGTH = 648;

  double PORTAL_WALL_OFFSET = 29.7;

  double SWITCH_LENGTH = 153.5;

  double SWITCH_WIDTH = 56;
  double SCALE_WIDTH = 50;
  double SCALE_SIDE_LENGTH = 36;

  double EDGE_OF_NULL_ZONE_TO_SCALE_PLATE_EDGE = 24.125;

  double SCALE_PLATE_TO_SIDE_WALL = 71.57;
  double SCALE_PLATE_TO_WALL = 299.65;
  double SCALE_LENGTH = FIELD_WIDTH - 2 * SCALE_PLATE_TO_SIDE_WALL;

  // double ROBOT_Y_TO_SCALE = SCALE_PLATE_TO_SIDE_WALL/2;
  // double ROBOT_Y_TO_SCALE = SCALE_PLATE_TO_SIDE_WALL-ROBOT_LENGTH;
  // double ROBOT_X_TO_SCALE = ROBOT_LENGTH/2;
  double ROBOT_Y_OFFSET_FROM_CENTER = 12;

  double NULL_ZONE_EDGE_TO_WALL = SCALE_PLATE_TO_WALL - EDGE_OF_NULL_ZONE_TO_SCALE_PLATE_EDGE;
  double ROBOT_TO_NULL_ZONE_EDGE = 275;

  double SWITCH_CENTER_FROM_WALL = 168;
  double SWITCH_EDGE_FROM_WALL = 140;
  double SWITCH_OUTER_EDGE_FROM_WALL = 196;
  double SWITCH_SCALE_MIDPOINT = (SWITCH_OUTER_EDGE_FROM_WALL + SCALE_PLATE_TO_WALL) / 2;

  double ROBOT_TO_SIDE = PORTAL_WALL_OFFSET + (ROBOT_WIDTH / 2);

  double SWITCH_CENTER_TO_PLATE_EDGE = 58.75;
  double SWITCH_EDGE_TO_SIDE_WALL = 85.25;
  double ROBOT_TO_SWITCH = SWITCH_EDGE_FROM_WALL - ROBOT_LENGTH;
  double ROBOT_TO_SWITCH_CENTER = ROBOT_TO_SWITCH + (SWITCH_WIDTH / 2);
  double ROBOT_CENTER_X_TURN_POINT = ROBOT_TO_SWITCH / 2;
  double ROBOT_CENTER_Y_TURN_POINT = SWITCH_CENTER_TO_PLATE_EDGE / 2;
  double SWITCH_HOOK_Y_DISTANCE = SWITCH_EDGE_TO_SIDE_WALL - ROBOT_TO_SIDE;
  double SWITCH_HOOK_TURN_X = ROBOT_TO_SWITCH_CENTER - ROBOT_LENGTH;
  double SWITCH_HOOK_TURN_Y = SWITCH_HOOK_Y_DISTANCE / 2;

  double ROBOT_TO_SCALE_CENTER = SCALE_PLATE_TO_WALL - ROBOT_LENGTH + (SCALE_WIDTH / 2);
  double ROBOT_TO_SCALE_X = SCALE_PLATE_TO_WALL - ROBOT_LENGTH;

  double SCALE_HOOK_TURN_X = ROBOT_TO_SCALE_CENTER - ROBOT_LENGTH;
  double SCALE_HOOK_Y_DISTANCE = SCALE_PLATE_TO_SIDE_WALL - ROBOT_TO_SIDE;

  double OTHER_SCALE_TURN = SCALE_HOOK_Y_DISTANCE + SCALE_SIDE_LENGTH;
  double OTHER_SCALE_TOTAL_Y = FIELD_WIDTH - ROBOT_TO_SIDE - SCALE_PLATE_TO_SIDE_WALL - SCALE_SIDE_LENGTH / 2;
  double OTHER_SCALE_MIDPOINT_Y = OTHER_SCALE_TOTAL_Y - 2 * OTHER_SCALE_TURN;
  double OTHER_SCALE_MIDPOINT_X = SWITCH_SCALE_MIDPOINT - ROBOT_LENGTH;

  double SWITCH_DROP_HEIGHT = 30; // outer encoder: actual ht=ht*2
  double SCALE_DROP_HEIGHT = 70; //

}
