#!/bin/sh

ps -ef | grep -w FRCUserProgram | awk '{print $2}' | xargs kill
ps -ef | grep -w gazebo | awk '{print $2}' | xargs kill -9
ps -ef | grep -w gzserver | awk '{print $2}' | xargs kill
ps -ef | grep -w gzclient | awk '{print $2}' | xargs kill

